'use client'

import React, { useState, useEffect, useCallback, useRef } from 'react'
import { AnimatePresence, type Transition, motion } from 'motion/react'
import type { Media as MediaType } from '@/payload-types'
import { PaginationDot } from '@/components/uui/application/pagination/pagination-dot'
import RichText from '@/components/RichText'
import { OptimizedImage } from '@/components/OptimizedImage'
import { cx } from '@/utilities/cx'
import './testimonials.css'

// Type will be auto-generated by Payload when types are regenerated
type TestimonialsBlockType = any
type TestimonialItem = any

interface TestimonialsBlockProps extends TestimonialsBlockType {
  blockType: 'testimonials'
}

const transition: Transition = {
  type: 'tween',
  duration: 0.6,
  ease: [0.32, 0.72, 0, 1], // Custom cubic-bezier for smooth easing
}

// Card background styles matching the system
const cardBackgroundStyles = {
  none: '',
  primary: 'bg-primary shadow-xs',
  'primary-reversed': 'bg-primary-reversed shadow-xs',
  secondary: 'bg-secondary shadow-xs',
  tertiary: 'bg-tertiary shadow-xs',
  accent: 'bg-accent shadow-xs',
  outline: 'border-2 border-border-primary',
}

// Spacing styles
const spacingStyles = {
  compact: 'py-12 md:py-16',
  normal: 'py-16 md:py-24',
  spacious: 'py-24 md:py-32',
}

export const TestimonialsBlock: React.FC<TestimonialsBlockProps> = ({
  selectedTestimonials,
  rotationDelay = 8,
  cardBackground = 'none',
  spacing = 'normal',
}) => {
  const [currentIndex, setCurrentIndex] = useState(0)
  const [isPaused, setIsPaused] = useState(false)
  const [maxHeight, setMaxHeight] = useState<number>(0)
  const intervalRef = useRef<NodeJS.Timeout | null>(null)
  const containerRef = useRef<HTMLDivElement>(null)
  const cardRefs = useRef<(HTMLDivElement | null)[]>([])

  // Filter out invalid testimonials and get valid array
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const testimonials = (selectedTestimonials?.filter(
    (t: any): t is TestimonialItem => typeof t === 'object' && t !== null,
  ) || []) as TestimonialItem[]

  const totalTestimonials = testimonials.length

  // Calculate maximum height from all testimonials
  useEffect(() => {
    const calculateMaxHeight = () => {
      if (cardRefs.current.length > 0) {
        const heights = cardRefs.current
          .filter((ref): ref is HTMLDivElement => ref !== null)
          .map((ref) => ref.offsetHeight)

        if (heights.length > 0) {
          const max = Math.max(...heights)
          setMaxHeight(max)
        }
      }
    }

    // Initial calculation with delay to ensure DOM is ready
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        calculateMaxHeight()
      })
    })

    // Recalculate on window resize
    const handleResize = () => {
      calculateMaxHeight()
    }

    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [testimonials])

  // Check for reduced motion preference
  const prefersReducedMotion =
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
      : false

  // Navigate to next testimonial
  const goToNext = useCallback(() => {
    setCurrentIndex((prev) => (prev + 1) % totalTestimonials)
  }, [totalTestimonials])

  // Navigate to previous testimonial
  const goToPrevious = useCallback(() => {
    setCurrentIndex((prev) => (prev - 1 + totalTestimonials) % totalTestimonials)
  }, [totalTestimonials])

  // Auto-rotation effect
  useEffect(() => {
    if (totalTestimonials <= 1 || isPaused || prefersReducedMotion) {
      return
    }

    intervalRef.current = setInterval(() => {
      goToNext()
    }, rotationDelay * 1000)

    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current)
      }
    }
  }, [totalTestimonials, isPaused, rotationDelay, goToNext, prefersReducedMotion])

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'ArrowLeft') {
        goToPrevious()
      } else if (e.key === 'ArrowRight') {
        goToNext()
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [goToNext, goToPrevious])

  // Handle drag end
  const handleDragEnd = (
    _event: MouseEvent | TouchEvent | PointerEvent,
    info: { offset: { x: number } },
  ) => {
    const dragThreshold = 50 // pixels

    if (info.offset.x > dragThreshold) {
      goToPrevious()
    } else if (info.offset.x < -dragThreshold) {
      goToNext()
    }
  }

  if (totalTestimonials === 0) {
    return null
  }

  const currentTestimonial = testimonials[currentIndex]
  const showAnimation = totalTestimonials > 1 && !prefersReducedMotion

  return (
    <section
      className={cx('', spacingStyles[spacing as keyof typeof spacingStyles])}
      role="region"
      aria-label="Customer testimonials"
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      <div className="mx-auto max-w-container px-4 md:px-8">
        {/* Hidden measurement container - renders all testimonials off-screen */}
        <div
          className="pointer-events-none absolute left-0 top-0 w-full opacity-0"
          style={{ visibility: 'hidden', position: 'absolute', zIndex: -1 }}
          aria-hidden="true"
        >
          <div className="mx-auto max-w-container px-4 md:px-8">
            <div className="flex w-full max-w-270 flex-col gap-8">
              {testimonials.map((testimonial, index) => (
                <div
                  key={index}
                  ref={(el) => {
                    cardRefs.current[index] = el
                  }}
                  className={cx(
                    'flex flex-col justify-center gap-6 rounded-2xl p-10 md:p-14',
                    cardBackgroundStyles[cardBackground as keyof typeof cardBackgroundStyles],
                  )}
                >
                  <TestimonialContent testimonial={testimonial} />
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="flex flex-col items-center gap-10">
          <div
            ref={containerRef}
            className={cx(
              'flex w-full max-w-270 flex-col gap-8 text-center',
              showAnimation && 'cursor-grab active:cursor-grabbing',
            )}
          >
            {showAnimation ? (
              <AnimatePresence initial={false} mode="popLayout">
                <motion.div
                  key={currentIndex}
                  drag={showAnimation ? 'x' : false}
                  dragConstraints={{ left: 0, right: 0 }}
                  dragElastic={0.2}
                  onDragEnd={handleDragEnd}
                  initial={{
                    opacity: 0,
                    x: 200,
                  }}
                  animate={{
                    opacity: 1,
                    x: 0,
                    transition: {
                      ...transition,
                      delay: 0.2,
                    },
                  }}
                  exit={{
                    opacity: 0,
                    x: -200,
                    transition,
                  }}
                  style={{ 
                    height: maxHeight > 0 ? `${maxHeight}px` : 'auto',
                  }}
                  className={cx(
                    'flex flex-col justify-center gap-6 rounded-2xl p-10 md:p-14',
                    cardBackgroundStyles[cardBackground as keyof typeof cardBackgroundStyles],
                  )}
                  aria-live="polite"
                  aria-atomic="true"
                >
                  <TestimonialContent testimonial={currentTestimonial} />
                </motion.div>
              </AnimatePresence>
            ) : (
              <div
                style={{ 
                  height: maxHeight > 0 ? `${maxHeight}px` : 'auto',
                }}
                className={cx(
                  'flex flex-col justify-center gap-6 rounded-2xl p-10 md:p-14',
                  cardBackgroundStyles[cardBackground as keyof typeof cardBackgroundStyles],
                )}
              >
                <TestimonialContent testimonial={currentTestimonial} />
              </div>
            )}
          </div>

          {totalTestimonials > 1 && (
            <div className="testimonials-pagination">
              <PaginationDot
                page={currentIndex + 1}
                total={totalTestimonials}
                size="lg"
                onPageChange={(page) => setCurrentIndex(page - 1)}
              />
            </div>
          )}
        </div>
      </div>
    </section>
  )
}

// Separate component for testimonial content
const TestimonialContent = React.forwardRef<HTMLDivElement, { testimonial: TestimonialItem }>(
  ({ testimonial }, ref) => {
    if (typeof testimonial === 'string') return null

    const { content, person, position, company, logo } = testimonial

    return (
      <div ref={ref} className="flex flex-col items-center justify-center gap-6 h-full">
        {/* Testimonial content (quote) */}
        {content && (
          <div className="w-full">
            <RichText data={content} enableGutter={false} enableProse={true} />
          </div>
        )}

        {/* Author details */}
        {(person || position || company || logo) && (
          <figcaption className="flex flex-col items-center gap-4">
            <div className="flex flex-col gap-2">
              {person && (
                <p className="text-lg font-semibold text-(--color-accent-500)">{person}</p>
              )}
              {(position || company) && (
                <div className="flex flex-col gap-0.5">
                  {position && <cite className="text-md text-tertiary not-italic">{position}</cite>}
                  {company && <cite className="text-md text-tertiary not-italic">{company}</cite>}
                </div>
              )}
            </div>

            {/* Company logo */}
            {logo && typeof logo === 'object' && (
              <div className="mt-2 flex items-center justify-center opacity-50 grayscale">
                <OptimizedImage
                  resource={logo as MediaType}
                  alt={`${company || person || ''} logo`}
                  className="max-h-8 w-auto object-contain"
                />
              </div>
            )}
          </figcaption>
        )}
      </div>
    )
  },
)

TestimonialContent.displayName = 'TestimonialContent'
