'use client'

import React, { useState, useEffect, useRef, useMemo } from 'react'
import { AnimatePresence, type Transition, motion } from 'motion/react'
import type { Media as MediaType } from '@/payload-types'
import { PaginationDot } from '@/components/uui/application/pagination/pagination-dot'
import RichText from '@/components/RichText'
import { OptimizedImage } from '@/components/OptimizedImage'
import { cx } from '@/utilities/cx'
import { cn } from '@/utilities/ui'
import {
  getBackgroundClasses,
  getTextColorClasses,
  type BackgroundVariant,
} from '@/utilities/backgroundVariants'
import { useCarouselAnimation } from '@/hooks/useCarouselAnimation'
import './testimonials.css'

// Type will be auto-generated by Payload when types are regenerated
type TestimonialsBlockType = any
type TestimonialItem = any

interface TestimonialsBlockProps extends TestimonialsBlockType {
  blockType: 'testimonials'
}

const transition: Transition = {
  type: 'tween',
  duration: 0.8,
  ease: [0.32, 0.72, 0, 1], // Custom cubic-bezier for smooth easing
}

// Spacing styles
const spacingStyles = {
  compact: 'py-12 md:py-16',
  normal: 'py-16 md:py-24',
  spacious: 'py-24 md:py-32',
}

// Animated testimonial wrapper
const AnimatedTestimonial: React.FC<{
  testimonial: TestimonialItem
  cardBackground: string
  direction: 'left' | 'right'
  transition: Transition
  onDragEnd: (
    event: MouseEvent | TouchEvent | PointerEvent,
    info: { offset: { x: number } },
  ) => void
  showAnimation: boolean
}> = ({ testimonial, cardBackground, direction, transition, onDragEnd, showAnimation }) => {
  return (
    <motion.div
      drag={showAnimation ? 'x' : false}
      dragConstraints={{ left: 0, right: 0 }}
      dragElastic={0.2}
      onDragEnd={onDragEnd}
      initial={{
        opacity: 0,
        x: direction === 'right' ? 200 : -200,
      }}
      animate={{
        opacity: 1,
        x: 0,
        transition: {
          ...transition,
          delay: 0.15, // Delay so incoming follows outgoing
        },
      }}
      exit={{
        opacity: 0,
        x: direction === 'right' ? -200 : 200, // Both use same direction for follow effect
        transition: {
          ...transition,
          delay: 0, // Exit starts immediately
        },
      }}
      className="absolute inset-0 flex w-full flex-col justify-center text-center px-10 md:px-20"
      aria-live="polite"
      aria-atomic="true"
    >
      <TestimonialContent testimonial={testimonial} cardBackground={cardBackground} />
    </motion.div>
  )
}

export const TestimonialsBlock: React.FC<TestimonialsBlockProps> = ({
  selectedTestimonials,
  rotationDelay = 8,
  enableAutoRotation = true,
  cardBackground = 'none',
  spacing = 'normal',
}) => {
  const [maxHeight, setMaxHeight] = useState<number>(0)
  const [transitionDirection, setTransitionDirection] = useState<'left' | 'right'>('right')
  const _containerRef = useRef<HTMLDivElement>(null)
  const cardRefs = useRef<(HTMLDivElement | null)[]>([])

  // Preserve order of selected testimonials
  const testimonials = useMemo(() => {
    if (!selectedTestimonials?.length) return []

    // Extract testimonial IDs in the order they were selected
    const testimonialIds = selectedTestimonials
      .map((t: any) => (typeof t === 'object' && t !== null ? t.id : t))
      .filter((id: unknown): id is string => typeof id === 'string')

    // Filter out invalid testimonials
    const validTestimonials = selectedTestimonials.filter(
      (t: any): t is TestimonialItem => typeof t === 'object' && t !== null,
    ) as TestimonialItem[]

    // Sort testimonials to match the selection order
    return validTestimonials.sort((a, b) => {
      const aIndex = testimonialIds.indexOf(a.id)
      const bIndex = testimonialIds.indexOf(b.id)
      // If ID not found, put at end
      if (aIndex === -1) return 1
      if (bIndex === -1) return -1
      return aIndex - bIndex
    })
  }, [selectedTestimonials])

  const totalTestimonials = testimonials.length

  // Use carousel animation hook
  const { currentIndex, direction, goToNext, goToPrevious, goToIndex, handleDragEnd } =
    useCarouselAnimation({
      totalItems: totalTestimonials,
      autoRotateDelay: rotationDelay,
      enableAutoRotate: enableAutoRotation,
    })

  // Calculate maximum height from all testimonials
  useEffect(() => {
    const calculateMaxHeight = () => {
      if (cardRefs.current.length > 0) {
        const heights = cardRefs.current
          .filter((ref): ref is HTMLDivElement => ref !== null)
          .map((ref) => ref.offsetHeight)

        if (heights.length > 0) {
          const max = Math.max(...heights)
          setMaxHeight(max)
        }
      }
    }

    // Initial calculation with delay to ensure DOM is ready
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        calculateMaxHeight()
      })
    })

    // Recalculate on window resize
    const handleResize = () => {
      calculateMaxHeight()
    }

    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [testimonials])

  // Check for reduced motion preference
  const prefersReducedMotion =
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
      : false

  // Sync transitionDirection with direction changes
  // This ensures both exiting and incoming elements use the same direction
  useEffect(() => {
    setTransitionDirection(direction)
  }, [direction])

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'ArrowLeft') {
        goToPrevious()
      } else if (e.key === 'ArrowRight') {
        goToNext()
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [goToNext, goToPrevious])

  // Handle drag end wrapper
  const onDragEnd = (
    _event: MouseEvent | TouchEvent | PointerEvent,
    info: { offset: { x: number } },
  ) => {
    handleDragEnd(info.offset)
  }

  if (totalTestimonials === 0) {
    return null
  }

  const currentTestimonial = testimonials[currentIndex]
  const showAnimation = totalTestimonials > 1 && !prefersReducedMotion
  const isLineVariant = cardBackground === 'line'

  return (
    <section
      className={cx('', spacingStyles[spacing as keyof typeof spacingStyles])}
      role="region"
      aria-label="Customer testimonials"
    >
      <div className="mx-auto max-w-container px-4 md:px-8">
        {/* Hidden measurement container - renders all testimonials off-screen */}
        <div
          className="pointer-events-none absolute left-0 top-0 w-full opacity-0"
          style={{ visibility: 'hidden', position: 'absolute', zIndex: -1 }}
          aria-hidden="true"
        >
          <div className="mx-auto max-w-container px-4 md:px-8">
            <div className="flex border-accent-500 border-2 w-full flex-col gap-8">
              {testimonials.map((testimonial, index) => (
                <div
                  key={index}
                  ref={(el) => {
                    cardRefs.current[index] = el
                  }}
                  className={cx(
                    'flex flex-col justify-center gap-6 p-10 md:px-20 md:py-14',
                    !isLineVariant && 'rounded-2xl',
                    getBackgroundClasses(cardBackground as BackgroundVariant),
                  )}
                >
                  <TestimonialContent testimonial={testimonial} cardBackground={cardBackground} />
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="flex flex-col items-center gap-10">
          {/* Static background container */}
          <div
            className={cx(
              'relative flex w-full flex-col justify-center gap-6 p-10 md:px-20 md:py-14 overflow-hidden',
              !isLineVariant && 'rounded-xl',
              getBackgroundClasses(cardBackground as BackgroundVariant),
              showAnimation && 'cursor-grab active:cursor-grabbing',
            )}
            style={{
              height: maxHeight > 0 ? `${maxHeight}px` : 'auto',
              willChange: 'transform',
            }}
          >
            {showAnimation ? (
              <AnimatePresence initial={false} mode="popLayout">
                <AnimatedTestimonial
                  key={`${currentIndex}-${transitionDirection}`}
                  testimonial={currentTestimonial}
                  cardBackground={cardBackground}
                  direction={transitionDirection}
                  transition={transition}
                  onDragEnd={onDragEnd}
                  showAnimation={showAnimation}
                />
              </AnimatePresence>
            ) : (
              <div className="flex w-full flex-col text-center">
                <TestimonialContent
                  testimonial={currentTestimonial}
                  cardBackground={cardBackground}
                />
              </div>
            )}
          </div>

          {totalTestimonials > 1 && (
            <div className="testimonials-pagination">
              <PaginationDot
                page={currentIndex + 1}
                total={totalTestimonials}
                size="lg"
                onPageChange={(page) => {
                  goToIndex(page - 1)
                }}
              />
            </div>
          )}
        </div>
      </div>
    </section>
  )
}

// Separate component for testimonial content
const TestimonialContent = React.forwardRef<
  HTMLDivElement,
  { testimonial: TestimonialItem; cardBackground?: string }
>(({ testimonial, cardBackground = 'none' }, ref) => {
  if (typeof testimonial === 'string') return null

  const { content, person, position, company, logo } = testimonial
  const textClasses = getTextColorClasses(cardBackground as BackgroundVariant)

  return (
    <div ref={ref} className="flex flex-col items-center justify-center gap-6 h-full">
      {/* Testimonial content (quote) */}
      {content && (
        <div className="w-full">
          <RichText
            data={content}
            enableGutter={false}
            enableProse={true}
            className={textClasses.richText}
          />
        </div>
      )}

      {/* Author details */}
      {(person || position || company || logo) && (
        <figcaption className="flex flex-col items-center gap-4">
          <div className="flex flex-col gap-2">
            {person && <p className={cn('text-lg font-semibold', textClasses.accent)}>{person}</p>}
            {(position || company) && (
              <div className="flex flex-col gap-0.5">
                {position && (
                  <cite className={cn('text-md not-italic', textClasses.muted)}>{position}</cite>
                )}
                {company && (
                  <cite className={cn('text-md not-italic', textClasses.muted)}>{company}</cite>
                )}
              </div>
            )}
          </div>

          {/* Company logo */}
          {logo && typeof logo === 'object' && (
            <div className="mt-2 flex items-center justify-center opacity-50 grayscale">
              <OptimizedImage
                resource={logo as MediaType}
                alt={`${company || person || ''} logo`}
                className="max-h-8 w-auto object-contain"
              />
            </div>
          )}
        </figcaption>
      )}
    </div>
  )
})

TestimonialContent.displayName = 'TestimonialContent'
