import type { CollectionConfig } from 'payload'
import { processSVGHook } from './Icons/hooks/processSVG'
import { enhanceWithAIHook } from './Icons/hooks/enhanceWithAI'

export const Icons: CollectionConfig = {
  slug: 'icons',
  admin: {
    useAsTitle: 'label',
    defaultColumns: ['icon', 'label', 'category', 'name'],
    description: 'Manage SVG icons for use throughout the site',
    pagination: {
      defaultLimit: 50,
    },
  },
  access: {
    read: () => true,
    create: ({ req: { user } }) => Boolean(user),
    update: ({ req: { user } }) => Boolean(user),
    delete: ({ req: { user } }) => Boolean(user),
  },
  fields: [
    {
      name: 'icon',
      type: 'ui',
      admin: {
        components: {
          Cell: '@/components/IconAI/IconCell',
        },
      },
    },
    {
      name: 'name',
      type: 'text',
      label: 'Icon Name',
      required: true,
      unique: true,
      admin: {
        description: 'Unique identifier for the icon (e.g., "home", "settings")',
        placeholder: 'home',
      },
      validate: (value: string | undefined | null | string[]) => {
        // Handle array values (for hasMany fields)
        if (Array.isArray(value)) {
          return 'Name must be a single value'
        }

        // Check for required value
        if (!value) return 'Name is required'

        // Type guard for string validation
        if (typeof value === 'string' && !/^[a-z0-9-_]+$/.test(value)) {
          return 'Name must be lowercase with only letters, numbers, hyphens, and underscores'
        }
        return true
      },
    },
    {
      name: 'label',
      type: 'text',
      label: 'Display Label',
      required: true,
      admin: {
        description: 'Human-readable name for the icon',
        placeholder: 'Home Icon',
      },
    },
    {
      name: 'iconPreview',
      type: 'ui',
      admin: {
        components: {
          Field: '@/components/IconAI/IconPreview',
        },
      },
    },
    {
      name: 'category',
      type: 'select',
      label: 'Category',
      defaultValue: 'interface',
      options: [
        { label: 'Navigation', value: 'navigation' },
        { label: 'Action', value: 'action' },
        { label: 'Social', value: 'social' },
        { label: 'Communication', value: 'communication' },
        { label: 'Interface', value: 'interface' },
        { label: 'File', value: 'file' },
        { label: 'Device', value: 'device' },
        { label: 'Commerce', value: 'commerce' },
        { label: 'Media', value: 'media' },
        { label: 'Custom', value: 'custom' },
      ],
      admin: {
        description: 'Category for organizing icons (can be AI-suggested)',
      },
    },
    {
      name: 'svgCode',
      type: 'code',
      label: 'SVG Code',
      required: true,
      admin: {
        language: 'xml',
        description: 'Optimized SVG code (will be processed to use currentColor)',
      },
    },
    {
      name: 'originalSvg',
      type: 'code',
      label: 'Original SVG',
      admin: {
        language: 'xml',
        description: 'Original SVG before optimization (backup)',
        hidden: true, // Hidden by default but available if needed
      },
    },
    {
      name: 'keywords',
      type: 'array',
      label: 'Keywords',
      labels: {
        singular: 'Keyword',
        plural: 'Keywords',
      },
      admin: {
        description: 'Keywords for search (automatically generated by AI on upload)',
        components: {
          RowLabel: '@/collections/Icons/components/KeywordRowLabel#KeywordRowLabel',
        },
      },
      fields: [
        {
          name: 'keyword',
          type: 'text',
          required: true,
        },
      ],
    },
    {
      name: 'description',
      type: 'text',
      label: 'Description',
      admin: {
        description: 'Brief description of the icon (automatically generated by AI on upload)',
        placeholder: 'Icon representing home or main dashboard',
      },
    },
    {
      name: 'tags',
      type: 'array',
      label: 'Tags',
      labels: {
        singular: 'Tag',
        plural: 'Tags',
      },
      admin: {
        description: 'Additional tags for categorization',
        components: {
          RowLabel: '@/collections/Icons/components/TagRowLabel#TagRowLabel',
        },
      },
      fields: [
        {
          name: 'tag',
          type: 'text',
          required: true,
        },
      ],
    },
    {
      name: 'metadata',
      type: 'group',
      label: 'Metadata',
      admin: {
        description: 'Technical metadata about the icon',
      },
      fields: [
        {
          name: 'width',
          type: 'number',
          label: 'Width',
          admin: {
            description: 'Original width in pixels',
            readOnly: true,
          },
        },
        {
          name: 'height',
          type: 'number',
          label: 'Height',
          admin: {
            description: 'Original height in pixels',
            readOnly: true,
          },
        },
        {
          name: 'viewBox',
          type: 'text',
          label: 'ViewBox',
          admin: {
            description: 'SVG viewBox attribute',
            readOnly: true,
          },
        },
        {
          name: 'pathCount',
          type: 'number',
          label: 'Path Count',
          admin: {
            description: 'Number of path elements',
            readOnly: true,
          },
        },
        {
          name: 'fileSize',
          type: 'number',
          label: 'File Size',
          admin: {
            description: 'Size in bytes after optimization',
            readOnly: true,
          },
        },
      ],
    },
    {
      name: 'aiMetadata',
      type: 'group',
      label: 'AI Enhancement',
      admin: {
        description: 'AI-generated metadata and enhancements',
      },
      fields: [
        {
          name: 'enhancedAt',
          type: 'date',
          label: 'Enhanced Date',
          admin: {
            description: 'When AI last processed this icon',
            readOnly: true,
          },
        },
        {
          name: 'model',
          type: 'text',
          label: 'AI Model',
          admin: {
            description: 'Model used for enhancement',
            readOnly: true,
          },
        },
        {
          name: 'confidence',
          type: 'number',
          label: 'Confidence Score',
          min: 0,
          max: 100,
          admin: {
            description: 'AI confidence in categorization (0-100)',
            readOnly: true,
          },
        },
      ],
    },
    {
      name: 'usage',
      type: 'group',
      label: 'Usage Statistics',
      admin: {
        description: 'Track where and how often this icon is used',
      },
      fields: [
        {
          name: 'count',
          type: 'number',
          label: 'Usage Count',
          defaultValue: 0,
          admin: {
            description: 'Number of times this icon is used',
            readOnly: true,
          },
        },
        {
          name: 'lastUsed',
          type: 'date',
          label: 'Last Used',
          admin: {
            description: 'Last time this icon was referenced',
            readOnly: true,
          },
        },
        {
          name: 'locations',
          type: 'array',
          label: 'Used In',
          admin: {
            description: 'Where this icon is used',
            readOnly: true,
          },
          fields: [
            {
              name: 'collectionSlug',
              type: 'text',
              label: 'Collection',
            },
            {
              name: 'field',
              type: 'text',
              label: 'Field',
            },
            {
              name: 'id',
              type: 'text',
              label: 'Document ID',
            },
          ],
        },
      ],
    },
  ],
  hooks: {
    beforeChange: [processSVGHook, enhanceWithAIHook],
  },
  timestamps: true,
}
