import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_blocks_cta_links_link_uui_size" ADD VALUE 'sm' BEFORE 'md';
  ALTER TYPE "public"."enum_pages_blocks_cta_links_link_uui_size" ADD VALUE 'xl';
  ALTER TYPE "public"."enum_pages_blocks_content_columns_link_uui_size" ADD VALUE 'xl';
  ALTER TYPE "public"."enum_pages_blocks_features_features_link_uui_size" ADD VALUE 'xl';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_size" ADD VALUE 'sm' BEFORE 'md';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_size" ADD VALUE 'xl';
  ALTER TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_size" ADD VALUE 'xl';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_link_uui_size" ADD VALUE 'xl';
  ALTER TYPE "public"."enum_header_cta_button_link_uui_color" ADD VALUE 'accent' BEFORE 'secondary';
  ALTER TYPE "public"."enum_header_cta_button_link_uui_color" ADD VALUE 'link';
  ALTER TYPE "public"."enum_header_cta_button_link_uui_size" ADD VALUE 'xl';
  ALTER TYPE "public"."enum_footer_nav_columns_items_link_uui_size" ADD VALUE 'sm' BEFORE 'lg';
  ALTER TYPE "public"."enum_footer_nav_columns_items_link_uui_size" ADD VALUE 'md' BEFORE 'lg';
  ALTER TYPE "public"."enum_footer_nav_columns_items_link_uui_size" ADD VALUE 'xl';
  ALTER TYPE "public"."enum_not_found_link_uui_color" ADD VALUE 'accent' BEFORE 'secondary';
  ALTER TYPE "public"."enum_not_found_link_uui_color" ADD VALUE 'tertiary';
  ALTER TYPE "public"."enum_not_found_link_uui_color" ADD VALUE 'link';
  ALTER TYPE "public"."enum_not_found_link_uui_size" ADD VALUE 'sm' BEFORE 'md';
  ALTER TYPE "public"."enum_not_found_link_uui_size" ADD VALUE 'xl';
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_cta_links_link_uui_color";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_cta_links_link_uui_color";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_content_columns_link_uui_color";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_content_columns_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_content_columns_link_uui_color";
  ALTER TABLE "pages_blocks_button_block_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_button_block_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_button_block_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_button_block_buttons_link_uui_color";
  ALTER TABLE "pages_blocks_button_block_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_button_block_buttons_link_uui_color";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::text;
  DROP TYPE "public"."enum_pages_blocks_features_features_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_features_features_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::"public"."enum_pages_blocks_features_features_link_uui_color";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_features_features_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_features_features_link_uui_color";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_cta_links_link_uui_color";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_cta_links_link_uui_color";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_content_columns_link_uui_color";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_content_columns_link_uui_color";
  ALTER TABLE "_pages_v_blocks_button_block_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_button_block_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_button_block_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_button_block_buttons_link_uui_color";
  ALTER TABLE "_pages_v_blocks_button_block_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_button_block_buttons_link_uui_color";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::"public"."enum__pages_v_blocks_features_features_link_uui_color";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_features_features_link_uui_color";
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::text;
  DROP TYPE "public"."enum_footer_nav_columns_items_link_uui_color";
  CREATE TYPE "public"."enum_footer_nav_columns_items_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::"public"."enum_footer_nav_columns_items_link_uui_color";
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_footer_nav_columns_items_link_uui_color" USING "link_uui_color"::"public"."enum_footer_nav_columns_items_link_uui_color";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color" ADD VALUE 'link-gray';
  ALTER TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color" ADD VALUE 'link-color';
  ALTER TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color" ADD VALUE 'primary-destructive';
  ALTER TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color" ADD VALUE 'secondary-destructive';
  ALTER TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color" ADD VALUE 'tertiary-destructive';
  ALTER TYPE "public"."enum_pages_blocks_button_block_buttons_link_uui_color" ADD VALUE 'link-destructive';
  ALTER TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color" ADD VALUE 'link-gray';
  ALTER TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color" ADD VALUE 'link-color';
  ALTER TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color" ADD VALUE 'primary-destructive';
  ALTER TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color" ADD VALUE 'secondary-destructive';
  ALTER TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color" ADD VALUE 'tertiary-destructive';
  ALTER TYPE "public"."enum__pages_v_blocks_button_block_buttons_link_uui_color" ADD VALUE 'link-destructive';
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_uui_color" AS ENUM('primary', 'secondary', 'tertiary', 'link-color');
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_cta_links_link_uui_color";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_cta_links_link_uui_color";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_size" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_size" SET DEFAULT 'lg'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_uui_size";
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_uui_size" AS ENUM('md', 'lg');
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_size" SET DEFAULT 'lg'::"public"."enum_pages_blocks_cta_links_link_uui_size";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_size" SET DATA TYPE "public"."enum_pages_blocks_cta_links_link_uui_size" USING "link_uui_size"::"public"."enum_pages_blocks_cta_links_link_uui_size";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_uui_color" AS ENUM('primary', 'secondary', 'tertiary', 'link-color');
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_content_columns_link_uui_color";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_content_columns_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_content_columns_link_uui_color";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_size" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_uui_size";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_uui_size" AS ENUM('sm', 'md', 'lg');
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::"public"."enum_pages_blocks_content_columns_link_uui_size";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_size" SET DATA TYPE "public"."enum_pages_blocks_content_columns_link_uui_size" USING "link_uui_size"::"public"."enum_pages_blocks_content_columns_link_uui_size";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link-color'::text;
  DROP TYPE "public"."enum_pages_blocks_features_features_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_features_features_link_uui_color" AS ENUM('primary', 'secondary', 'tertiary', 'link-color', 'link-gray');
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link-color'::"public"."enum_pages_blocks_features_features_link_uui_color";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_features_features_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_features_features_link_uui_color";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_size" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::text;
  DROP TYPE "public"."enum_pages_blocks_features_features_link_uui_size";
  CREATE TYPE "public"."enum_pages_blocks_features_features_link_uui_size" AS ENUM('sm', 'md', 'lg');
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::"public"."enum_pages_blocks_features_features_link_uui_size";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_size" SET DATA TYPE "public"."enum_pages_blocks_features_features_link_uui_size" USING "link_uui_size"::"public"."enum_pages_blocks_features_features_link_uui_size";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color" AS ENUM('primary', 'secondary', 'tertiary', 'link-color');
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_cta_links_link_uui_color";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_cta_links_link_uui_color";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_size" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_size" SET DEFAULT 'lg'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_size";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_size" AS ENUM('md', 'lg');
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_size" SET DEFAULT 'lg'::"public"."enum__pages_v_blocks_cta_links_link_uui_size";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_size" SET DATA TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_size" USING "link_uui_size"::"public"."enum__pages_v_blocks_cta_links_link_uui_size";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color" AS ENUM('primary', 'secondary', 'tertiary', 'link-color');
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_content_columns_link_uui_color";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_content_columns_link_uui_color";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_size" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_size";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_size" AS ENUM('sm', 'md', 'lg');
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::"public"."enum__pages_v_blocks_content_columns_link_uui_size";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_size" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_size" USING "link_uui_size"::"public"."enum__pages_v_blocks_content_columns_link_uui_size";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link-color'::text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color" AS ENUM('primary', 'secondary', 'tertiary', 'link-color', 'link-gray');
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link-color'::"public"."enum__pages_v_blocks_features_features_link_uui_color";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_features_features_link_uui_color";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_size" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_link_uui_size";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_link_uui_size" AS ENUM('sm', 'md', 'lg');
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::"public"."enum__pages_v_blocks_features_features_link_uui_size";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_size" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_link_uui_size" USING "link_uui_size"::"public"."enum__pages_v_blocks_features_features_link_uui_size";
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_color" SET DATA TYPE text;
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_header_cta_button_link_uui_color";
  CREATE TYPE "public"."enum_header_cta_button_link_uui_color" AS ENUM('primary', 'secondary', 'tertiary');
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_color" SET DEFAULT 'primary'::"public"."enum_header_cta_button_link_uui_color";
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_color" SET DATA TYPE "public"."enum_header_cta_button_link_uui_color" USING "cta_button_link_uui_color"::"public"."enum_header_cta_button_link_uui_color";
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_size" SET DATA TYPE text;
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_size" SET DEFAULT 'sm'::text;
  DROP TYPE "public"."enum_header_cta_button_link_uui_size";
  CREATE TYPE "public"."enum_header_cta_button_link_uui_size" AS ENUM('sm', 'md', 'lg');
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_size" SET DEFAULT 'sm'::"public"."enum_header_cta_button_link_uui_size";
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_size" SET DATA TYPE "public"."enum_header_cta_button_link_uui_size" USING "cta_button_link_uui_size"::"public"."enum_header_cta_button_link_uui_size";
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_color" SET DEFAULT 'link-gray'::text;
  DROP TYPE "public"."enum_footer_nav_columns_items_link_uui_color";
  CREATE TYPE "public"."enum_footer_nav_columns_items_link_uui_color" AS ENUM('link-gray');
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_color" SET DEFAULT 'link-gray'::"public"."enum_footer_nav_columns_items_link_uui_color";
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_footer_nav_columns_items_link_uui_color" USING "link_uui_color"::"public"."enum_footer_nav_columns_items_link_uui_color";
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_size" SET DATA TYPE text;
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_size" SET DEFAULT 'lg'::text;
  DROP TYPE "public"."enum_footer_nav_columns_items_link_uui_size";
  CREATE TYPE "public"."enum_footer_nav_columns_items_link_uui_size" AS ENUM('lg');
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_size" SET DEFAULT 'lg'::"public"."enum_footer_nav_columns_items_link_uui_size";
  ALTER TABLE "footer_nav_columns_items" ALTER COLUMN "link_uui_size" SET DATA TYPE "public"."enum_footer_nav_columns_items_link_uui_size" USING "link_uui_size"::"public"."enum_footer_nav_columns_items_link_uui_size";
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_not_found_link_uui_color";
  CREATE TYPE "public"."enum_not_found_link_uui_color" AS ENUM('primary', 'secondary');
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_not_found_link_uui_color";
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_not_found_link_uui_color" USING "link_uui_color"::"public"."enum_not_found_link_uui_color";
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_size" SET DATA TYPE text;
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::text;
  DROP TYPE "public"."enum_not_found_link_uui_size";
  CREATE TYPE "public"."enum_not_found_link_uui_size" AS ENUM('md', 'lg');
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_size" SET DEFAULT 'md'::"public"."enum_not_found_link_uui_size";
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_size" SET DATA TYPE "public"."enum_not_found_link_uui_size" USING "link_uui_size"::"public"."enum_not_found_link_uui_size";`)
}
