import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_blocks_hero_heading_buttons_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_pages_blocks_hero_heading_headline_color" ADD VALUE 'white' BEFORE 'brand';
  ALTER TYPE "public"."enum_pages_blocks_hero_heading_hero_background" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum_pages_blocks_hero_heading_hero_background" ADD VALUE 'tertiary' BEFORE 'accent';
  ALTER TYPE "public"."enum_pages_blocks_cta_links_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_pages_blocks_content_columns_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_pages_blocks_card_grid_cards_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_pages_blocks_card_grid_card_background" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum_pages_blocks_card_grid_card_background" ADD VALUE 'tertiary' BEFORE 'accent';
  ALTER TYPE "public"."enum_pages_blocks_card_grid_icon_color" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum_pages_blocks_features_features_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_pages_blocks_features_layout_options_card_background" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum_pages_blocks_features_layout_options_card_background" ADD VALUE 'tertiary' BEFORE 'accent';
  ALTER TYPE "public"."enum_pages_blocks_features_layout_options_icon_color" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum_pages_blocks_latest_posts_button_config_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_heading_buttons_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_heading_headline_color" ADD VALUE 'white' BEFORE 'brand';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_heading_hero_background" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_heading_hero_background" ADD VALUE 'tertiary' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_card_grid_card_background" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum__pages_v_blocks_card_grid_card_background" ADD VALUE 'tertiary' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_card_grid_icon_color" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_features_layout_options_card_background" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum__pages_v_blocks_features_layout_options_card_background" ADD VALUE 'tertiary' BEFORE 'accent';
  ALTER TYPE "public"."enum__pages_v_blocks_features_layout_options_icon_color" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum__pages_v_blocks_latest_posts_button_config_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_posts_blocks_latest_posts_button_config_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_posts_blocks_cta_links_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum__posts_v_blocks_latest_posts_button_config_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum__posts_v_blocks_cta_links_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_header_cta_button_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_header_mobile_cta_button_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_not_found_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_posts_settings_blocks_hero_heading_buttons_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_posts_settings_blocks_hero_heading_headline_color" ADD VALUE 'white' BEFORE 'brand';
  ALTER TYPE "public"."enum_posts_settings_blocks_hero_heading_hero_background" ADD VALUE 'primary-reversed' BEFORE 'secondary';
  ALTER TYPE "public"."enum_posts_settings_blocks_hero_heading_hero_background" ADD VALUE 'tertiary' BEFORE 'accent';
  ALTER TYPE "public"."enum_posts_settings_blocks_cta_links_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TYPE "public"."enum_posts_settings_blocks_content_columns_link_uui_color" ADD VALUE 'primary-reversed' BEFORE 'accent';
  ALTER TABLE "pages_blocks_hero_heading" DROP COLUMN "subheading_color";
  ALTER TABLE "_pages_v_blocks_hero_heading" DROP COLUMN "subheading_color";
  ALTER TABLE "posts_settings_blocks_hero_heading" DROP COLUMN "subheading_color";
  DROP TYPE "public"."enum_pages_blocks_hero_heading_subheading_color";
  DROP TYPE "public"."enum__pages_v_blocks_hero_heading_subheading_color";
  DROP TYPE "public"."enum_posts_settings_blocks_hero_heading_subheading_color";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_hero_heading_subheading_color" AS ENUM('default', 'white');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_heading_subheading_color" AS ENUM('default', 'white');
  CREATE TYPE "public"."enum_posts_settings_blocks_hero_heading_subheading_color" AS ENUM('default', 'white');
  ALTER TABLE "pages_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_hero_heading_buttons_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_hero_heading_buttons_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary');
  ALTER TABLE "pages_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_hero_heading_buttons_link_uui_color";
  ALTER TABLE "pages_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_hero_heading_buttons_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_hero_heading_buttons_link_uui_color";
  ALTER TABLE "pages_blocks_hero_heading" ALTER COLUMN "headline_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_hero_heading" ALTER COLUMN "headline_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_hero_heading_headline_color";
  CREATE TYPE "public"."enum_pages_blocks_hero_heading_headline_color" AS ENUM('primary', 'brand');
  ALTER TABLE "pages_blocks_hero_heading" ALTER COLUMN "headline_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_hero_heading_headline_color";
  ALTER TABLE "pages_blocks_hero_heading" ALTER COLUMN "headline_color" SET DATA TYPE "public"."enum_pages_blocks_hero_heading_headline_color" USING "headline_color"::"public"."enum_pages_blocks_hero_heading_headline_color";
  ALTER TABLE "pages_blocks_hero_heading" ALTER COLUMN "hero_background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_hero_heading" ALTER COLUMN "hero_background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_hero_heading_hero_background";
  CREATE TYPE "public"."enum_pages_blocks_hero_heading_hero_background" AS ENUM('primary', 'secondary', 'accent');
  ALTER TABLE "pages_blocks_hero_heading" ALTER COLUMN "hero_background" SET DEFAULT 'primary'::"public"."enum_pages_blocks_hero_heading_hero_background";
  ALTER TABLE "pages_blocks_hero_heading" ALTER COLUMN "hero_background" SET DATA TYPE "public"."enum_pages_blocks_hero_heading_hero_background" USING "hero_background"::"public"."enum_pages_blocks_hero_heading_hero_background";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_cta_links_link_uui_color";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_cta_links_link_uui_color";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_content_columns_link_uui_color";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_content_columns_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_content_columns_link_uui_color";
  ALTER TABLE "pages_blocks_card_grid_cards" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_card_grid_cards" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::text;
  DROP TYPE "public"."enum_pages_blocks_card_grid_cards_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_card_grid_cards_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_card_grid_cards" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::"public"."enum_pages_blocks_card_grid_cards_link_uui_color";
  ALTER TABLE "pages_blocks_card_grid_cards" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_card_grid_cards_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_card_grid_cards_link_uui_color";
  ALTER TABLE "pages_blocks_card_grid" ALTER COLUMN "card_background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_card_grid" ALTER COLUMN "card_background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_card_grid_card_background";
  CREATE TYPE "public"."enum_pages_blocks_card_grid_card_background" AS ENUM('primary', 'secondary', 'accent', 'line');
  ALTER TABLE "pages_blocks_card_grid" ALTER COLUMN "card_background" SET DEFAULT 'primary'::"public"."enum_pages_blocks_card_grid_card_background";
  ALTER TABLE "pages_blocks_card_grid" ALTER COLUMN "card_background" SET DATA TYPE "public"."enum_pages_blocks_card_grid_card_background" USING "card_background"::"public"."enum_pages_blocks_card_grid_card_background";
  ALTER TABLE "pages_blocks_card_grid" ALTER COLUMN "icon_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_card_grid" ALTER COLUMN "icon_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_card_grid_icon_color";
  CREATE TYPE "public"."enum_pages_blocks_card_grid_icon_color" AS ENUM('primary', 'secondary', 'tertiary', 'accent');
  ALTER TABLE "pages_blocks_card_grid" ALTER COLUMN "icon_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_card_grid_icon_color";
  ALTER TABLE "pages_blocks_card_grid" ALTER COLUMN "icon_color" SET DATA TYPE "public"."enum_pages_blocks_card_grid_icon_color" USING "icon_color"::"public"."enum_pages_blocks_card_grid_icon_color";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::text;
  DROP TYPE "public"."enum_pages_blocks_features_features_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_features_features_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::"public"."enum_pages_blocks_features_features_link_uui_color";
  ALTER TABLE "pages_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_features_features_link_uui_color" USING "link_uui_color"::"public"."enum_pages_blocks_features_features_link_uui_color";
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "layout_options_card_background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "layout_options_card_background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_features_layout_options_card_background";
  CREATE TYPE "public"."enum_pages_blocks_features_layout_options_card_background" AS ENUM('primary', 'secondary', 'accent', 'line');
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "layout_options_card_background" SET DEFAULT 'primary'::"public"."enum_pages_blocks_features_layout_options_card_background";
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "layout_options_card_background" SET DATA TYPE "public"."enum_pages_blocks_features_layout_options_card_background" USING "layout_options_card_background"::"public"."enum_pages_blocks_features_layout_options_card_background";
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "layout_options_icon_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "layout_options_icon_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_features_layout_options_icon_color";
  CREATE TYPE "public"."enum_pages_blocks_features_layout_options_icon_color" AS ENUM('primary', 'secondary', 'tertiary', 'accent');
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "layout_options_icon_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_features_layout_options_icon_color";
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "layout_options_icon_color" SET DATA TYPE "public"."enum_pages_blocks_features_layout_options_icon_color" USING "layout_options_icon_color"::"public"."enum_pages_blocks_features_layout_options_icon_color";
  ALTER TABLE "pages_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_latest_posts_button_config_link_uui_color";
  CREATE TYPE "public"."enum_pages_blocks_latest_posts_button_config_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "pages_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DEFAULT 'primary'::"public"."enum_pages_blocks_latest_posts_button_config_link_uui_color";
  ALTER TABLE "pages_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DATA TYPE "public"."enum_pages_blocks_latest_posts_button_config_link_uui_color" USING "button_config_link_uui_color"::"public"."enum_pages_blocks_latest_posts_button_config_link_uui_color";
  ALTER TABLE "_pages_v_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_heading_buttons_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_heading_buttons_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary');
  ALTER TABLE "_pages_v_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_hero_heading_buttons_link_uui_color";
  ALTER TABLE "_pages_v_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_hero_heading_buttons_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_hero_heading_buttons_link_uui_color";
  ALTER TABLE "_pages_v_blocks_hero_heading" ALTER COLUMN "headline_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_hero_heading" ALTER COLUMN "headline_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_heading_headline_color";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_heading_headline_color" AS ENUM('primary', 'brand');
  ALTER TABLE "_pages_v_blocks_hero_heading" ALTER COLUMN "headline_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_hero_heading_headline_color";
  ALTER TABLE "_pages_v_blocks_hero_heading" ALTER COLUMN "headline_color" SET DATA TYPE "public"."enum__pages_v_blocks_hero_heading_headline_color" USING "headline_color"::"public"."enum__pages_v_blocks_hero_heading_headline_color";
  ALTER TABLE "_pages_v_blocks_hero_heading" ALTER COLUMN "hero_background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_hero_heading" ALTER COLUMN "hero_background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_heading_hero_background";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_heading_hero_background" AS ENUM('primary', 'secondary', 'accent');
  ALTER TABLE "_pages_v_blocks_hero_heading" ALTER COLUMN "hero_background" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_hero_heading_hero_background";
  ALTER TABLE "_pages_v_blocks_hero_heading" ALTER COLUMN "hero_background" SET DATA TYPE "public"."enum__pages_v_blocks_hero_heading_hero_background" USING "hero_background"::"public"."enum__pages_v_blocks_hero_heading_hero_background";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_cta_links_link_uui_color";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_cta_links_link_uui_color";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_content_columns_link_uui_color";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_content_columns_link_uui_color";
  ALTER TABLE "_pages_v_blocks_card_grid_cards" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_card_grid_cards" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::text;
  DROP TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_card_grid_cards" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::"public"."enum__pages_v_blocks_card_grid_cards_link_uui_color";
  ALTER TABLE "_pages_v_blocks_card_grid_cards" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_card_grid_cards_link_uui_color";
  ALTER TABLE "_pages_v_blocks_card_grid" ALTER COLUMN "card_background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_card_grid" ALTER COLUMN "card_background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_card_grid_card_background";
  CREATE TYPE "public"."enum__pages_v_blocks_card_grid_card_background" AS ENUM('primary', 'secondary', 'accent', 'line');
  ALTER TABLE "_pages_v_blocks_card_grid" ALTER COLUMN "card_background" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_card_grid_card_background";
  ALTER TABLE "_pages_v_blocks_card_grid" ALTER COLUMN "card_background" SET DATA TYPE "public"."enum__pages_v_blocks_card_grid_card_background" USING "card_background"::"public"."enum__pages_v_blocks_card_grid_card_background";
  ALTER TABLE "_pages_v_blocks_card_grid" ALTER COLUMN "icon_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_card_grid" ALTER COLUMN "icon_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_card_grid_icon_color";
  CREATE TYPE "public"."enum__pages_v_blocks_card_grid_icon_color" AS ENUM('primary', 'secondary', 'tertiary', 'accent');
  ALTER TABLE "_pages_v_blocks_card_grid" ALTER COLUMN "icon_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_card_grid_icon_color";
  ALTER TABLE "_pages_v_blocks_card_grid" ALTER COLUMN "icon_color" SET DATA TYPE "public"."enum__pages_v_blocks_card_grid_icon_color" USING "icon_color"::"public"."enum__pages_v_blocks_card_grid_icon_color";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::text;
  DROP TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DEFAULT 'link'::"public"."enum__pages_v_blocks_features_features_link_uui_color";
  ALTER TABLE "_pages_v_blocks_features_features" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_features_features_link_uui_color" USING "link_uui_color"::"public"."enum__pages_v_blocks_features_features_link_uui_color";
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "layout_options_card_background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "layout_options_card_background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_features_layout_options_card_background";
  CREATE TYPE "public"."enum__pages_v_blocks_features_layout_options_card_background" AS ENUM('primary', 'secondary', 'accent', 'line');
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "layout_options_card_background" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_features_layout_options_card_background";
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "layout_options_card_background" SET DATA TYPE "public"."enum__pages_v_blocks_features_layout_options_card_background" USING "layout_options_card_background"::"public"."enum__pages_v_blocks_features_layout_options_card_background";
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "layout_options_icon_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "layout_options_icon_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_features_layout_options_icon_color";
  CREATE TYPE "public"."enum__pages_v_blocks_features_layout_options_icon_color" AS ENUM('primary', 'secondary', 'tertiary', 'accent');
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "layout_options_icon_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_features_layout_options_icon_color";
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "layout_options_icon_color" SET DATA TYPE "public"."enum__pages_v_blocks_features_layout_options_icon_color" USING "layout_options_icon_color"::"public"."enum__pages_v_blocks_features_layout_options_icon_color";
  ALTER TABLE "_pages_v_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_latest_posts_button_config_link_uui_color";
  CREATE TYPE "public"."enum__pages_v_blocks_latest_posts_button_config_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_pages_v_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_latest_posts_button_config_link_uui_color";
  ALTER TABLE "_pages_v_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DATA TYPE "public"."enum__pages_v_blocks_latest_posts_button_config_link_uui_color" USING "button_config_link_uui_color"::"public"."enum__pages_v_blocks_latest_posts_button_config_link_uui_color";
  ALTER TABLE "posts_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_posts_blocks_latest_posts_button_config_link_uui_color";
  CREATE TYPE "public"."enum_posts_blocks_latest_posts_button_config_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "posts_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DEFAULT 'primary'::"public"."enum_posts_blocks_latest_posts_button_config_link_uui_color";
  ALTER TABLE "posts_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DATA TYPE "public"."enum_posts_blocks_latest_posts_button_config_link_uui_color" USING "button_config_link_uui_color"::"public"."enum_posts_blocks_latest_posts_button_config_link_uui_color";
  ALTER TABLE "posts_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_posts_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum_posts_blocks_cta_links_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "posts_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_posts_blocks_cta_links_link_uui_color";
  ALTER TABLE "posts_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_posts_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum_posts_blocks_cta_links_link_uui_color";
  ALTER TABLE "_posts_v_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_posts_v_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__posts_v_blocks_latest_posts_button_config_link_uui_color";
  CREATE TYPE "public"."enum__posts_v_blocks_latest_posts_button_config_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_posts_v_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DEFAULT 'primary'::"public"."enum__posts_v_blocks_latest_posts_button_config_link_uui_color";
  ALTER TABLE "_posts_v_blocks_latest_posts" ALTER COLUMN "button_config_link_uui_color" SET DATA TYPE "public"."enum__posts_v_blocks_latest_posts_button_config_link_uui_color" USING "button_config_link_uui_color"::"public"."enum__posts_v_blocks_latest_posts_button_config_link_uui_color";
  ALTER TABLE "_posts_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "_posts_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__posts_v_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum__posts_v_blocks_cta_links_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "_posts_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum__posts_v_blocks_cta_links_link_uui_color";
  ALTER TABLE "_posts_v_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum__posts_v_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum__posts_v_blocks_cta_links_link_uui_color";
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_color" SET DATA TYPE text;
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_header_cta_button_link_uui_color";
  CREATE TYPE "public"."enum_header_cta_button_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_color" SET DEFAULT 'primary'::"public"."enum_header_cta_button_link_uui_color";
  ALTER TABLE "header" ALTER COLUMN "cta_button_link_uui_color" SET DATA TYPE "public"."enum_header_cta_button_link_uui_color" USING "cta_button_link_uui_color"::"public"."enum_header_cta_button_link_uui_color";
  ALTER TABLE "header" ALTER COLUMN "mobile_cta_button_link_uui_color" SET DATA TYPE text;
  ALTER TABLE "header" ALTER COLUMN "mobile_cta_button_link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_header_mobile_cta_button_link_uui_color";
  CREATE TYPE "public"."enum_header_mobile_cta_button_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "header" ALTER COLUMN "mobile_cta_button_link_uui_color" SET DEFAULT 'primary'::"public"."enum_header_mobile_cta_button_link_uui_color";
  ALTER TABLE "header" ALTER COLUMN "mobile_cta_button_link_uui_color" SET DATA TYPE "public"."enum_header_mobile_cta_button_link_uui_color" USING "mobile_cta_button_link_uui_color"::"public"."enum_header_mobile_cta_button_link_uui_color";
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_not_found_link_uui_color";
  CREATE TYPE "public"."enum_not_found_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_not_found_link_uui_color";
  ALTER TABLE "not_found" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_not_found_link_uui_color" USING "link_uui_color"::"public"."enum_not_found_link_uui_color";
  ALTER TABLE "posts_settings_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "posts_settings_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_posts_settings_blocks_hero_heading_buttons_link_uui_color";
  CREATE TYPE "public"."enum_posts_settings_blocks_hero_heading_buttons_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary');
  ALTER TABLE "posts_settings_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_posts_settings_blocks_hero_heading_buttons_link_uui_color";
  ALTER TABLE "posts_settings_blocks_hero_heading_buttons" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_posts_settings_blocks_hero_heading_buttons_link_uui_color" USING "link_uui_color"::"public"."enum_posts_settings_blocks_hero_heading_buttons_link_uui_color";
  ALTER TABLE "posts_settings_blocks_hero_heading" ALTER COLUMN "headline_color" SET DATA TYPE text;
  ALTER TABLE "posts_settings_blocks_hero_heading" ALTER COLUMN "headline_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_posts_settings_blocks_hero_heading_headline_color";
  CREATE TYPE "public"."enum_posts_settings_blocks_hero_heading_headline_color" AS ENUM('primary', 'brand');
  ALTER TABLE "posts_settings_blocks_hero_heading" ALTER COLUMN "headline_color" SET DEFAULT 'primary'::"public"."enum_posts_settings_blocks_hero_heading_headline_color";
  ALTER TABLE "posts_settings_blocks_hero_heading" ALTER COLUMN "headline_color" SET DATA TYPE "public"."enum_posts_settings_blocks_hero_heading_headline_color" USING "headline_color"::"public"."enum_posts_settings_blocks_hero_heading_headline_color";
  ALTER TABLE "posts_settings_blocks_hero_heading" ALTER COLUMN "hero_background" SET DATA TYPE text;
  ALTER TABLE "posts_settings_blocks_hero_heading" ALTER COLUMN "hero_background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_posts_settings_blocks_hero_heading_hero_background";
  CREATE TYPE "public"."enum_posts_settings_blocks_hero_heading_hero_background" AS ENUM('primary', 'secondary', 'accent');
  ALTER TABLE "posts_settings_blocks_hero_heading" ALTER COLUMN "hero_background" SET DEFAULT 'primary'::"public"."enum_posts_settings_blocks_hero_heading_hero_background";
  ALTER TABLE "posts_settings_blocks_hero_heading" ALTER COLUMN "hero_background" SET DATA TYPE "public"."enum_posts_settings_blocks_hero_heading_hero_background" USING "hero_background"::"public"."enum_posts_settings_blocks_hero_heading_hero_background";
  ALTER TABLE "posts_settings_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "posts_settings_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_posts_settings_blocks_cta_links_link_uui_color";
  CREATE TYPE "public"."enum_posts_settings_blocks_cta_links_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "posts_settings_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_posts_settings_blocks_cta_links_link_uui_color";
  ALTER TABLE "posts_settings_blocks_cta_links" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_posts_settings_blocks_cta_links_link_uui_color" USING "link_uui_color"::"public"."enum_posts_settings_blocks_cta_links_link_uui_color";
  ALTER TABLE "posts_settings_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE text;
  ALTER TABLE "posts_settings_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_posts_settings_blocks_content_columns_link_uui_color";
  CREATE TYPE "public"."enum_posts_settings_blocks_content_columns_link_uui_color" AS ENUM('primary', 'accent', 'secondary', 'tertiary', 'link');
  ALTER TABLE "posts_settings_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DEFAULT 'primary'::"public"."enum_posts_settings_blocks_content_columns_link_uui_color";
  ALTER TABLE "posts_settings_blocks_content_columns" ALTER COLUMN "link_uui_color" SET DATA TYPE "public"."enum_posts_settings_blocks_content_columns_link_uui_color" USING "link_uui_color"::"public"."enum_posts_settings_blocks_content_columns_link_uui_color";
  ALTER TABLE "pages_blocks_hero_heading" ADD COLUMN "subheading_color" "enum_pages_blocks_hero_heading_subheading_color" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_hero_heading" ADD COLUMN "subheading_color" "enum__pages_v_blocks_hero_heading_subheading_color" DEFAULT 'default';
  ALTER TABLE "posts_settings_blocks_hero_heading" ADD COLUMN "subheading_color" "enum_posts_settings_blocks_hero_heading_subheading_color" DEFAULT 'default';`)
}
