import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_latest_posts_opts_sort_by" AS ENUM('date-desc', 'date-asc', 'title-asc', 'title-desc');
  CREATE TYPE "public"."enum_pages_blocks_latest_posts_card_display_excerpt_length" AS ENUM('short', 'medium', 'long');
  CREATE TYPE "public"."enum_pages_blocks_latest_posts_layout_options_display_mode" AS ENUM('auto', 'grid', 'carousel');
  CREATE TYPE "public"."peek_amt" AS ENUM('none', 'small', 'medium', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_latest_posts_opts_sort_by" AS ENUM('date-desc', 'date-asc', 'title-asc', 'title-desc');
  CREATE TYPE "public"."enum__pages_v_blocks_latest_posts_card_display_excerpt_length" AS ENUM('short', 'medium', 'long');
  CREATE TYPE "public"."enum__pages_v_blocks_latest_posts_layout_options_display_mode" AS ENUM('auto', 'grid', 'carousel');
  CREATE TYPE "public"."enum_posts_blocks_latest_posts_opts_sort_by" AS ENUM('date-desc', 'date-asc', 'title-asc', 'title-desc');
  CREATE TYPE "public"."enum_posts_blocks_latest_posts_card_display_excerpt_length" AS ENUM('short', 'medium', 'long');
  CREATE TYPE "public"."enum_posts_blocks_latest_posts_layout_options_display_mode" AS ENUM('auto', 'grid', 'carousel');
  CREATE TYPE "public"."enum__posts_v_blocks_latest_posts_opts_sort_by" AS ENUM('date-desc', 'date-asc', 'title-asc', 'title-desc');
  CREATE TYPE "public"."enum__posts_v_blocks_latest_posts_card_display_excerpt_length" AS ENUM('short', 'medium', 'long');
  CREATE TYPE "public"."enum__posts_v_blocks_latest_posts_layout_options_display_mode" AS ENUM('auto', 'grid', 'carousel');
  ALTER TABLE "pages_blocks_latest_posts" DROP CONSTRAINT "pages_blocks_latest_posts_opts_category_filter_id_categories_id_fk";
  
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP CONSTRAINT "_pages_v_blocks_latest_posts_opts_category_filter_id_categories_id_fk";
  
  ALTER TABLE "posts_blocks_latest_posts" DROP CONSTRAINT "posts_blocks_latest_posts_opts_category_filter_id_categories_id_fk";
  
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP CONSTRAINT "_posts_v_blocks_latest_posts_opts_category_filter_id_categories_id_fk";
  
  DROP INDEX "pages_blocks_latest_posts_opts_opts_category_filter_idx";
  DROP INDEX "_pages_v_blocks_latest_posts_opts_opts_category_filter_idx";
  DROP INDEX "posts_blocks_latest_posts_opts_opts_category_filter_idx";
  DROP INDEX "_posts_v_blocks_latest_posts_opts_opts_category_filter_idx";
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "opts_sort_by" "enum_pages_blocks_latest_posts_opts_sort_by" DEFAULT 'date-desc';
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "opts_show_featured_first" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "card_display_show_categories" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "card_display_show_author" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "card_display_show_date" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "card_display_show_reading_time" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "card_display_show_excerpt" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "card_display_excerpt_length" "enum_pages_blocks_latest_posts_card_display_excerpt_length" DEFAULT 'medium';
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "layout_options_display_mode" "enum_pages_blocks_latest_posts_layout_options_display_mode" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_enable_drag" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_show_arrows" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_show_progress" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_peek_amount" "peek_amt" DEFAULT 'medium';
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_auto_play" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_auto_play_interval" numeric DEFAULT 5000;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "opts_sort_by" "enum__pages_v_blocks_latest_posts_opts_sort_by" DEFAULT 'date-desc';
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "opts_show_featured_first" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "card_display_show_categories" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "card_display_show_author" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "card_display_show_date" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "card_display_show_reading_time" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "card_display_show_excerpt" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "card_display_excerpt_length" "enum__pages_v_blocks_latest_posts_card_display_excerpt_length" DEFAULT 'medium';
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "layout_options_display_mode" "enum__pages_v_blocks_latest_posts_layout_options_display_mode" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_enable_drag" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_show_arrows" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_show_progress" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_peek_amount" "peek_amt" DEFAULT 'medium';
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_auto_play" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_auto_play_interval" numeric DEFAULT 5000;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "opts_sort_by" "enum_posts_blocks_latest_posts_opts_sort_by" DEFAULT 'date-desc';
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "opts_show_featured_first" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "card_display_show_categories" boolean DEFAULT true;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "card_display_show_author" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "card_display_show_date" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "card_display_show_reading_time" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "card_display_show_excerpt" boolean DEFAULT true;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "card_display_excerpt_length" "enum_posts_blocks_latest_posts_card_display_excerpt_length" DEFAULT 'medium';
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "layout_options_display_mode" "enum_posts_blocks_latest_posts_layout_options_display_mode" DEFAULT 'auto';
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_enable_drag" boolean DEFAULT true;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_show_arrows" boolean DEFAULT true;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_show_progress" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_peek_amount" "peek_amt" DEFAULT 'medium';
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_auto_play" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_auto_play_interval" numeric DEFAULT 5000;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "opts_sort_by" "enum__posts_v_blocks_latest_posts_opts_sort_by" DEFAULT 'date-desc';
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "opts_show_featured_first" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "card_display_show_categories" boolean DEFAULT true;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "card_display_show_author" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "card_display_show_date" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "card_display_show_reading_time" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "card_display_show_excerpt" boolean DEFAULT true;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "card_display_excerpt_length" "enum__posts_v_blocks_latest_posts_card_display_excerpt_length" DEFAULT 'medium';
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "layout_options_display_mode" "enum__posts_v_blocks_latest_posts_layout_options_display_mode" DEFAULT 'auto';
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_enable_drag" boolean DEFAULT true;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_show_arrows" boolean DEFAULT true;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_show_progress" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_peek_amount" "peek_amt" DEFAULT 'medium';
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_auto_play" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "layout_options_carousel_options_auto_play_interval" numeric DEFAULT 5000;
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "opts_category_filter_id";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "opts_category_filter_id";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "opts_category_filter_id";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "opts_category_filter_id";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_latest_posts" ADD COLUMN "opts_category_filter_id" integer;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD COLUMN "opts_category_filter_id" integer;
  ALTER TABLE "posts_blocks_latest_posts" ADD COLUMN "opts_category_filter_id" integer;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD COLUMN "opts_category_filter_id" integer;
  ALTER TABLE "pages_blocks_latest_posts" ADD CONSTRAINT "pages_blocks_latest_posts_opts_category_filter_id_categories_id_fk" FOREIGN KEY ("opts_category_filter_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_latest_posts" ADD CONSTRAINT "_pages_v_blocks_latest_posts_opts_category_filter_id_categories_id_fk" FOREIGN KEY ("opts_category_filter_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "posts_blocks_latest_posts" ADD CONSTRAINT "posts_blocks_latest_posts_opts_category_filter_id_categories_id_fk" FOREIGN KEY ("opts_category_filter_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_posts_v_blocks_latest_posts" ADD CONSTRAINT "_posts_v_blocks_latest_posts_opts_category_filter_id_categories_id_fk" FOREIGN KEY ("opts_category_filter_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "pages_blocks_latest_posts_opts_opts_category_filter_idx" ON "pages_blocks_latest_posts" USING btree ("opts_category_filter_id");
  CREATE INDEX "_pages_v_blocks_latest_posts_opts_opts_category_filter_idx" ON "_pages_v_blocks_latest_posts" USING btree ("opts_category_filter_id");
  CREATE INDEX "posts_blocks_latest_posts_opts_opts_category_filter_idx" ON "posts_blocks_latest_posts" USING btree ("opts_category_filter_id");
  CREATE INDEX "_posts_v_blocks_latest_posts_opts_opts_category_filter_idx" ON "_posts_v_blocks_latest_posts" USING btree ("opts_category_filter_id");
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "opts_sort_by";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "opts_show_featured_first";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "card_display_show_categories";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "card_display_show_author";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "card_display_show_date";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "card_display_show_reading_time";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "card_display_show_excerpt";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "card_display_excerpt_length";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "layout_options_display_mode";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_enable_drag";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_show_arrows";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_show_progress";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_peek_amount";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_auto_play";
  ALTER TABLE "pages_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_auto_play_interval";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "opts_sort_by";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "opts_show_featured_first";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "card_display_show_categories";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "card_display_show_author";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "card_display_show_date";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "card_display_show_reading_time";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "card_display_show_excerpt";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "card_display_excerpt_length";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "layout_options_display_mode";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_enable_drag";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_show_arrows";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_show_progress";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_peek_amount";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_auto_play";
  ALTER TABLE "_pages_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_auto_play_interval";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "opts_sort_by";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "opts_show_featured_first";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "card_display_show_categories";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "card_display_show_author";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "card_display_show_date";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "card_display_show_reading_time";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "card_display_show_excerpt";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "card_display_excerpt_length";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "layout_options_display_mode";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_enable_drag";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_show_arrows";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_show_progress";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_peek_amount";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_auto_play";
  ALTER TABLE "posts_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_auto_play_interval";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "opts_sort_by";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "opts_show_featured_first";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "card_display_show_categories";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "card_display_show_author";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "card_display_show_date";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "card_display_show_reading_time";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "card_display_show_excerpt";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "card_display_excerpt_length";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "layout_options_display_mode";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_enable_drag";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_show_arrows";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_show_progress";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_peek_amount";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_auto_play";
  ALTER TABLE "_posts_v_blocks_latest_posts" DROP COLUMN "layout_options_carousel_options_auto_play_interval";
  DROP TYPE "public"."enum_pages_blocks_latest_posts_opts_sort_by";
  DROP TYPE "public"."enum_pages_blocks_latest_posts_card_display_excerpt_length";
  DROP TYPE "public"."enum_pages_blocks_latest_posts_layout_options_display_mode";
  DROP TYPE "public"."peek_amt";
  DROP TYPE "public"."enum__pages_v_blocks_latest_posts_opts_sort_by";
  DROP TYPE "public"."enum__pages_v_blocks_latest_posts_card_display_excerpt_length";
  DROP TYPE "public"."enum__pages_v_blocks_latest_posts_layout_options_display_mode";
  DROP TYPE "public"."enum_posts_blocks_latest_posts_opts_sort_by";
  DROP TYPE "public"."enum_posts_blocks_latest_posts_card_display_excerpt_length";
  DROP TYPE "public"."enum_posts_blocks_latest_posts_layout_options_display_mode";
  DROP TYPE "public"."enum__posts_v_blocks_latest_posts_opts_sort_by";
  DROP TYPE "public"."enum__posts_v_blocks_latest_posts_card_display_excerpt_length";
  DROP TYPE "public"."enum__posts_v_blocks_latest_posts_layout_options_display_mode";`)
}
